### ISSUE TITLE
IntrospectionError: Unable to find property 'key' in java.util.KeyValueHolder 

### ISSUE THREAD

**Issue by rupert-madden-abbott** [assertj/assertj#3543] opened 2024-07-16 15:56 UTC
**Describe the bug**

When upgrading from Java 11 to Java 21, a test has begun to fail because it can no longer extract a property, whereas previously, it could.

* assertj core version: 3.22.0 (also tried with 3.26.3
* java version: 21
* test framework version: junit 5.8.2

**Test case reproducing the bug**

The following works on Java 11 but fails on 21.

```java
        assertThat(List.of(Map.entry("foo", "bar")))
                .extracting("key")
                .containsExactly("foo");
```

with the following error:

```
org.assertj.core.util.introspection.IntrospectionError: 
Can't find any field or property with name 'key'.
Error when introspecting properties was :
- Unable to find property 'key' in java.util.KeyValueHolder 
Error when introspecting fields was :
- Unable to obtain the value of the field <'key'> from <foo=bar>

	at org.assertj.core.util.introspection.PropertyOrFieldSupport.getSimpleValue(PropertyOrFieldSupport.java:91)
	at org.assertj.core.util.introspection.PropertyOrFieldSupport.getValueOf(PropertyOrFieldSupport.java:61)
	at org.assertj.core.extractor.ByNameSingleExtractor.apply(ByNameSingleExtractor.java:29)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.assertj.core.groups.FieldsOrPropertiesExtractor.extract(FieldsOrPropertiesExtractor.java:64)
	at org.assertj.core.api.AbstractIterableAssert.extracting(AbstractIterableAssert.java:1070)
... snip ...
```

**Workaround**

Using this works fine instead:

```java
        assertThat(List.of(Map.entry("foo", "bar")))
                .extracting(Map.Entry::getKey)
                .containsExactly("foo");
```

**Comment by scordio** [comment] 2024-07-17 06:47
The root cause:

```
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field final java.lang.Object java.util.KeyValueHolder.key accessible: module java.base does not "opens java.util" to unnamed module @7a5d012c
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:391)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:367)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:315)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:183)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:177)
	at org.assertj.core.util.introspection.FieldUtils.getField(FieldUtils.java:72)
	at org.assertj.core.util.introspection.FieldUtils.readField(FieldUtils.java:167)
	at org.assertj.core.util.introspection.FieldSupport.readSimpleField(FieldSupport.java:208)
```

I strongly suggest the use of `Map.Entry::getKey`, as you already found out.

In case you need to stick to reflection, you have to add the following JVM argument to your test execution configuration:
```
--add-opens=java.base/java.util=ALL-UNNAMED
```

For example, you'd do the following with the `maven-surefire-plugin`:

```xml
<plugin> 
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-surefire-plugin</artifactId>
  <configuration>
    <argLine>
      --add-opens java.base/java.util=ALL-UNNAMED
    </argLine>
  </configuration>
</plugin>
```

In light of that, I'm closing the issue, but please let us know if there is anything else we can do to help.

**Closed by scordio** 2024-07-17 06:47 UTC
