### ISSUE TITLE
Equality comparison by properties

### ISSUE THREAD

**Issue by chrylis** [assertj/assertj#2314] opened 2021-08-16 17:10 UTC
#### Summary

When comparing values, AssertJ takes a very strong opinion that the objects are defined by their _fields_, which is contrary to general Java best practice and makes testing interface-based code difficult. It seems that AssertJ will internally use property-based access as some kind of fallback, but it has eager fast-fail on some very ordinary use cases.

Instead, AssertJ should _prefer_ property-based access when it's declared, and it should not perform invasive introspection if a perfectly suitable public property is available.

#### Example

```java
interface MailMessage {
  String getTemplate();
  InternetAddress getRecipient();
}

class HelloMessage implements MailMessage {
  @Override public final String getTemplate() { return "hello"; }
  @Getter @Setter InternetAddress recipient;
}

@Getter
@Setter
class GenericMessage implements MailMessage {
  String template;
  InternetAddress recipient;
}
```

In my code, I want to assert that, after processing, `var original = new HelloMessage()` and `var result // instanceof GenericMessage` have the same property values. However, trying to use `assertThat(result).usingRecursiveComparison().isEqualTo(original)` produces this error:

```
GenericMessage can't be compared to HelloMessage as  does not declare all GenericMessage fields, it lacks these: [template]
```

`template` is most certainly declared as a _property_, which is all that most infrastructure cares about, and the old `isEqualToComparingFieldByField`, even though named "field", handled this fine.

**Comment by cvnntg** [comment] 2021-08-17 00:07
Similarly, it would be nice if we could force PROPERTIES to be used, rather than fields.

Or another way to put it, I suppose, is to only use a property as a comparison if it has a get____() function built in.

**Comment by joel-costigliola** [comment] 2021-08-17 09:31
I agree, we already have created https://github.com/assertj/assertj-core/issues/2189, it is a wip but as it's rather complex I can't say when this will be addressed.

**Comment by joel-costigliola** [comment] 2022-10-24 04:24
@chrylis I'm finishing off https://github.com/assertj/assertj/issues/2189 which will allow to provide the way to introspect nodes to be compared in the recursive comparison (properties, fields ... implementor choice).

I try reproducing your issue but could not which I think is due to the use of https://github.com/assertj/assertj/blob/main/assertj-core/src/main/java/org/assertj/core/util/introspection/PropertyOrFieldSupport.java#L65 in the recursive comparison which looks at property first and field second.

Here's the code I ran which is a simplified version of your example:
```java
  @Test
  void should_pass_with_property_based_introspection() {
    // GIVEN
    Message actual = new HelloMessage();
    Message expected = new GenericMessage("hello");
    // WHEN/THEN
    then(actual).usingRecursiveComparison()
                .isEqualTo(expected);
  }

  interface Message {
    String getTemplate();
  }

  class HelloMessage implements Message {
    public final String getTemplate() {
      return "hello";
    }

  }

  class GenericMessage implements Message {
    String template;

    public GenericMessage(String template) {
      this.template = template;
    }

    @Override
    public String getTemplate() {
      return template;
    }
  }
```

**Comment by joel-costigliola** [comment] 2022-10-29 04:18
@chrylis , we have finally got the time to address  #2189 which is why I'm closing this issue.

I actually wrote a [test](https://github.com/assertj/assertj/blob/main/assertj-core/src/test/java/org/assertj/core/api/recursive/comparison/RecursiveComparisonAssert_isEqualTo_withIntrospectionStrategy_Test.java#L211) using an [introspection strategy](https://github.com/assertj/assertj/blob/main/assertj-core/src/test/java/org/assertj/core/api/recursive/comparison/RecursiveComparisonAssert_isEqualTo_withIntrospectionStrategy_Test.java#L229) that addresses this issue, see:

I'm planning to expose the `ComparingProperties` introspection strategy implementation in AssertJ so that it's available out of the box for users like yourself (we'll likely do the same with `ComparingFields`).

We need to discuss in the team to switch the default introspection strategy implementation to `ComparingProperties`, I'm closing this issue and might create another one to decide on the the default introspection strategy.

Feel free to comment on the issue if you feel it's not fully addressed and we'll be happy to reopen it.

**Closed by joel-costigliola** 2022-10-29 04:18 UTC
Labels: type: enhancement, theme: recursive comparison
