### ISSUE TITLE
ignoringCollectionOrder() in entity field

### ISSUE THREAD

**Issue by andreevich96** [assertj/assertj#2843] opened 2022-11-16 13:25 UTC
#### I need to compare existing all elements from array1 in array2.
I have an entity:
```
    @AllArgsConstructor
    @NoArgsConstructor
    @Getter
    @Setter
    @EqualsAndHashCode(callSuper = false)
    public static class PersonDto {
        private Integer personId;

        private String personInfo;

        public List<String> getPersonInfo() {
            return this.personInfo == null ? null : Arrays.asList(this.personInfo .split(";"));
        }
```
In the field personInfo I can have a value like: "lastName" or a few values separated by ";" - "lastName;firstName"

#### Example

```java
SoftAssertions softAssertions = new SoftAssertions();
expectedList.forEach(person-> softAssertions.assertThat(actualPersonList)
                        .usingRecursiveComparison()
                        .ignoringCollectionOrder()
                        .isIn(person)
                );
```
I'm trying to compare lists of this entities. I think .isIn() should work, but .ignoringCollectionOrder() don't ignoring order in the entity FIELD.
Could you please suggest a solution to this problem? Or assertJ can't resolve this yet?

**Comment by joel-costigliola** [comment] 2022-11-16 20:17
@andreevich96 could you add a reproducible test case, ideally without lombok annotations since we don't use them.

**Comment by andreevich96** [comment] 2022-11-21 06:50
This is a entity class:

```
import java.util.List;
import java.util.Objects;

public class PersonDto {
    private Integer personId;

    private List<String> personInfo;

    private Integer age;

    public PersonDto() {
    }

    public PersonDto(Integer personId, List<String> personInfo, Integer age) {
        this.personId = personId;
        this.personInfo = personInfo;
        this.age = age;
    }

    public Integer getPersonId() {
        return personId;
    }

    public void setPersonId(Integer personId) {
        this.personId = personId;
    }

    public List<String> getPersonInfo() {
        return personInfo;
    }

    public void setPersonInfo(List<String> personInfo) {
        this.personInfo = personInfo;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        PersonDto personDto = (PersonDto) o;
        return Objects.equals(personId, personDto.personId) && Objects.equals(personInfo, personDto.personInfo) && Objects.equals(age, personDto.age);
    }

    @Override
    public int hashCode() {
        return Objects.hash(personId, personInfo, age);
    }
}
```

Test class:

```
import org.assertj.core.api.SoftAssertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import ru.itasystems.monsys.tests.models.responses.PersonDto;

import java.util.ArrayList;
import java.util.List;

@DisplayName("Display name")
class PersonCheck {

    private final List<PersonDto> list1 = new ArrayList<>();
    private final List<PersonDto> list2 = new ArrayList<>();

    @Test
    @DisplayName("Test Name")
    void checkPersonListsGet() {
        PersonDto person1 = new PersonDto(10, List.of("John"), 25);
        PersonDto person2 = new PersonDto(20, List.of("Ben"), 30);
        PersonDto person3 = new PersonDto(30, List.of("Rick", "Sanchez"), 35);

        // Here is personInfo has the same value as in person3, but in another order
        PersonDto person4 = new PersonDto(30, List.of("Sanchez", "Rick"), 35);

        list1.addAll(List.of(person1, person2, person3));

        list2.addAll(List.of(person1, person2, person4));

        SoftAssertions softAssertions = new SoftAssertions();

        list2.forEach(person -> softAssertions.assertThat(person)
                .usingRecursiveComparison()
                .ignoringCollectionOrder()
                .isIn(list1)
        );
        softAssertions.assertAll();
    }
}
```

I want to assert this case, with ignoring collection order in entity field

**Comment by joel-costigliola** [comment] 2022-12-11 04:19
The issue is related to `isIn` which the recursive comparison does not support, it's an oversight from us so thanks for reporting it.

**Comment by joel-costigliola** [comment] 2022-12-14 09:43
Fixed by https://github.com/assertj/assertj/commit/37923fafb4fd5d2c0448b3a3180ff13f89b032fa

**Closed by joel-costigliola** 2022-12-14 09:43 UTC
Labels: theme: recursive comparison
