### ISSUE TITLE
NullPointerException for null collection in usingRecursiveAssertion()

### ISSUE THREAD

**Issue by tlinkowski** [assertj/assertj#3114] opened 2023-07-20 07:46 UTC
**Describe the bug**
AssertJ throws NPE on null collections/maps/optionals when `usingRecursiveAssertion()` is used.

* assertj core version: 3.24.2
* java version: 11
* test framework version: n/a
* os (if relevant): n/a

**Test case reproducing the bug**

```java
    static class Response {
        private final List<String> elements;

        public Response(List<String> elements) {
            this.elements = elements;
        }
    }

    @Test
    public void shouldNotThrowNPE() {
        var response = new Response(null);

        assertThat(response).usingRecursiveAssertion().hasNoNullFields();
    }
```

This throws:
```
java.lang.NullPointerException
	at org.assertj.core.api.recursive.assertion.RecursiveAssertionDriver.recurseIntoCollection(RecursiveAssertionDriver.java:158)
```

I believe AssertJ shouldn't try to recurse into collections/maps/optionals which are null.

Note that even using this doesn't help:
```java
        assertThat(response).usingRecursiveAssertion()
                .withCollectionAssertionPolicy(RecursiveAssertionConfiguration.CollectionAssertionPolicy.COLLECTION_OBJECT_AND_ELEMENTS)
                .hasNoNullFields();
```
because the assertion for null collection is added and the NPE is still generated later on.

**Comment by JitendraProgrammer** [comment] 2023-08-21 00:59
Hi @tlinkowski,

I am new in open source but as a Java engineer will try to help you guys, 

import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.Test;

import java.util.List;

public class ExampleTest {

    static class Response {
        private final List<String> elements;

        public Response(List<String> elements) {
            this.elements = elements;
        }
    }

    @Test
    public void shouldNotThrowNPE() {
        var response = new Response(null);

        Assertions.assertThat(response)
            .usingRecursiveComparison()
            .doesNotContainNull(); // Use doesNotContainNull() instead of hasNoNullFields()
    }
}

**Comment by joel-costigliola** [comment] 2023-08-21 21:42
@tlinkowski thanks for reporting the issue, we are a bit busy but will try to look at it in the next few days/weeks

**Comment by robinmatz** [comment] 2023-11-19 05:36
I tried looking into it. I was able to reproduce the error with 3.24.2, however I was not able to reproduce it with the current `main` branch.

Here are the different implementations 
```java
// RecursiveAssertionDriver.java
// 3.24.0

private void recurseIntoCollection(Predicate<Object> predicate, Collection<?> collection, FieldLocation fieldLocation) {
    // TODO handle collection if needed by policy
    int index = 0;
    for (Object element : collection) { // --> NPE is thrown here
      assertRecursively(predicate, element, safeGetClass(element), fieldLocation.field(format(INDEX_FORMAT, index)));
      index++;
    }
  }
```

vs. 
```java
// RecursiveAssertionDriver.java
// on main
 private void recurseIntoCollection(Predicate<Object> predicate, Collection<?> collection, FieldLocation fieldLocation) {
    // TODO handle collection if needed by policy
    if (collection == null) {
      return; // no way to recursive into the collection, anyway the collection node has already been visited
    }
    int index = 0;
    for (Object element : collection) {
      assertRecursively(predicate, element, safeGetClass(element), fieldLocation.field(format(INDEX_FORMAT, index)));
      index++;
    }
  }
```
  
  So, basically, there is no more iterating over the collection if it is `null`, which rids us of the NPE. However, if I run the test case provided by @tlinkowski with the below version, now it passes, which is not what I would expect either.

**Comment by robinmatz** [comment] 2023-11-19 06:26
I have to correct myself. I did not realize that the default CollectionAssertionPolicy is ELEMENTS_ONLY, i.e. the predicate is only applied to elements of the collection, but not to the collection itself.

Running the test with
```java
   assertThat(response).usingRecursiveAssertion()
                .withCollectionAssertionPolicy(RecursiveAssertionConfiguration.CollectionAssertionPolicy.COLLECTION_OBJECT_AND_ELEMENTS)
                .hasNoNullFields();
```

results in the expected error

```
java.lang.AssertionError: 
The following fields did not satisfy the predicate:
  [elements]
The recursive assertion was performed with this configuration:
- fields from Java Class Library types (java.* or javax.*) were excluded in the recursive assertion
- the collection assertion policy was COLLECTION_OBJECT_AND_ELEMENTS
- the map assertion policy was MAP_VALUES_ONLY
- the optional assertion policy was OPTIONAL_VALUE_ONLY
- the introspection strategy used was: DefaultRecursiveAssertionIntrospectionStrategy which introspects all fields (including inherited ones)
```

So, I think this issue has already been addressed and will be resolved with the next release.

**Comment by joel-costigliola** [comment] 2023-11-19 10:43
@robinmatz thanks for the investigation, yes I think we can close it as we have [this test](https://github.com/assertj/assertj/blob/a43b599e0175df71cc2faea4cdf751f94bbcee23/assertj-core/src/test/java/org/assertj/core/api/recursive/assertion/RecursiveAssertionAssert_hasNoNullFields_Test.java#L133) ensuring that the null collections are correctly reported: 
```java
  class OuterWithCollection {
    InnerWithCollection inner = new InnerWithCollection();
    Collection<String> collectionOuter = null;
  }

  @SuppressWarnings("unused")
  class InnerWithCollection {
    Collection<String> collectionInner = null;
  }

  @Test
  public void should_report_null_collections() {
    // GIVEN
    Object testObject = new OuterWithCollection();
    // WHEN
    AssertionError error = expectAssertionError(() -> assertThat(testObject).usingRecursiveAssertion()
                                                                            .withCollectionAssertionPolicy(COLLECTION_OBJECT_AND_ELEMENTS)
                                                                            .hasNoNullFields());
    // THEN
    then(error).hasMessageContainingAll("collectionOuter", "inner.collection");
  }
```

**Closed by joel-costigliola** 2023-11-19 10:43 UTC
Labels: theme: recursive comparison
