### ISSUE TITLE
Provide reason and possible replacement for  @Deprecated

### ISSUE THREAD

**Issue by maciejmiklas** [assertj/assertj#3380] opened 2024-02-26 11:24 UTC
#### Feature Summary

In IDE, we rely on JavaDoc, please document the Deprecated code so we can easily replace it with a recommended solution.

#### Example

```java
  @Deprecated
  @Override
  @CheckReturnValue
  public AbstractListAssert<?, List<?>, Object, ObjectAssert<Object>> asList() {
```

**Comment by scordio** [comment] 2024-02-26 12:36
But not mentioning on which version you're experiencing the issue, you don't find it unprofessional, right? 😉

**Comment by maciejmiklas** [comment] 2024-02-26 12:38
3.25.1

**Comment by scordio** [comment] 2024-02-26 12:39
Please upgrade to the latest version.

Closing as duplicate of #3327.

**Closed by scordio** 2024-02-26 12:39 UTC
Labels: status: duplicate
