### ISSUE TITLE
Add convenient values() extractor method in MapAssert

### ISSUE THREAD

**Issue by Skym0sh0** [assertj/assertj#2978] opened 2023-03-09 18:38 UTC
#### Feature summary
It would be nice if there was a method in MapAssert that returns a (Abstract)CollectionAssert over the values contained in the map.

Example:
```java
Assertions.assertThat(Map.of("str", 1))
	.values()
	.contains(1);
```

Currently I have to use the following:

```java
Assertions.assertThat(Map.of("str", 1))
	.extracting(Map::values, as(collection(Integer.class)))
	.contains(1);
```

**Comment by joel-costigliola** [comment] 2023-03-13 20:35
We are ok with this improvement, likely will provide `values()` to switch the object under test to a `Collection<Object>` and `values(Class valueType)` to a `Collection<Class>`.

**Comment by kang-mansher** [comment] 2023-04-02 16:53
Can I work on this improvement

**Comment by joel-costigliola** [comment] 2023-04-04 09:42
Sure go ahead @kang-mansher, thanks!

**Comment by igmtz** [comment] 2023-04-20 19:51
Hello @joel-costigliola can I contribute? 😄

**Comment by joel-costigliola** [comment] 2023-04-21 08:15
@kang-mansher are you still interested in contributing? if not @igmtz would be keen to.

**Comment by scordio** [comment] 2024-05-26 08:47
Closing as duplicate of #3291.

**Closed by scordio** 2024-05-26 08:47 UTC
Labels: status: duplicate
