### ISSUE TITLE
CSS on JavaDocs for vertical displays hides package names

### ISSUE THREAD

**Issue by ascopes** [assertj/assertj#2904] opened 2023-01-07 11:21 UTC
Not sure if this is an issue in the JavaDoc official CSS or not, but I just noticed that viewing the JavaDocs for 3.24.0 on a display that is vertically aligned seems to cut off the package names, making it difficult to see what they correspond to.

![Screenshot_2023-01-07-11-18-24-03_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/73482956/211147606-a853ef28-b653-438f-b5d5-84e0280d8510.jpg)

This *might* be specific to mobile devices, however, the display is slightly easier to read if I rotate the device horizontally.

Maybe setting the CSS so that tables overflow with scroll if their bounds go below, say, 1000px, may be a solution?

If not, the new-style default JavaDoc CSS does not seem to have this issue, so that may also be a potential consideration. Example of one of my projects using that, on the same device:

![Screenshot_2023-01-07-11-25-47-91_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/73482956/211147919-605520c7-2f3a-420d-9297-aaf569bad153.jpg)

**Comment by scordio** [comment] 2023-01-07 15:17
This has been caused by 9391f541aa440a1de1fb2c7d805a51add677cfd6 and fbcbb2baff89ead5539d30b005797dcd9da30a18.

After removing the custom stylesheet, everything looks good:

![localhost_63342_assertj_assertj-core_target_site_apidocs_index html__ijt=7hp0qskr87t5f8fvdlj4hpijp4 _ij_reload=RELOAD_ON_SAVE](https://user-images.githubusercontent.com/26772046/211157817-d393d224-dcae-4d54-b92e-95e87b481e69.png)

**Comment by ascopes** [comment] 2023-01-08 10:10
That looks a lot better!

**Comment by scordio** [comment] 2023-12-17 21:33
To be checked again once #3191 is merged.

**Comment by scordio** [comment] 2023-12-28 21:28
This looks better now:

![Screen Shot 2023-12-28 at 22 27 51](https://github.com/assertj/assertj/assets/26772046/1ff5c4a4-d06b-4039-8216-071a91c36378)

**Closed by scordio** 2023-12-28 21:28 UTC
Labels: type: bug, theme: documentation
