### ISSUE TITLE
Recursive comparison depends on the sequence of objects.

### ISSUE THREAD

**Issue by pparas007** [assertj/assertj#3326] opened 2024-01-09 13:22 UTC
Description:
It is observed that the result of recursive comparison depends on the sequence of objects used. 
It looks like if the 2nd object(used in "isEqualTo()") has more fields than the 1st object(used in "assertThat()"), the assertion passes.
But if the sequence is exchanged, it fails.

assertj core version: 3.19.0
java version: 11
test framework version: JUnit 4.3.12

Test case reproducing the bug:
```java
@Test
    public void test1() {
        class SampleClass {
            String value1;
            SampleClass(String value) {
                this.value1 = value;
            }
        }
        class SampleClass2 extends SampleClass {
            String value2;
            SampleClass2(String value1, String value2) {
                super(value1);
                this.value2 = value2;
            }
        }
        SampleClass object1 = new SampleClass("value1");
        SampleClass2 object2 = new SampleClass2("value1", "value2");
        assertThat(object1).usingRecursiveComparison().isEqualTo(object2); // this passes
        assertThat(object2).usingRecursiveComparison().isEqualTo(object1); // this fails
    }
```

**Comment by scordio** [comment] 2024-01-09 13:25
Hi @pparas007, you're using a three year old version 😉 

Could you check your example against 3.25.1?

**Comment by pparas007** [comment] 2024-01-10 11:31
tried upping the version to 3.25.1. Still the same issue.

**Comment by pparas007** [comment] 2024-02-16 11:03
any updates here? thanks!

**Comment by scordio** [comment] 2024-02-17 08:25
As mentioned in the [docs](https://assertj.github.io/doc/#basic-usage), this is by design:

> The comparison is **not symmetrical** since it is **limited to `actual` fields**.
>
> The algorithm gathers `actual` fields and then compares them to the corresponding `expected` fields. It is then possible for the `expected` object to have more fields than `actual`, which can be handy when comparing a base type to a subtype with additional fields.

In lights of this, I close the issue but let us know if there is anything else.

**Closed by scordio** 2024-02-17 08:25 UTC
Labels: theme: recursive comparison
