### ISSUE TITLE
Comparable interfaces can't be checked with isGreater/isLess directly

### ISSUE THREAD

**Issue by xenoterracide** [assertj/assertj#3431] opened 2024-04-16 16:13 UTC
#### Feature summary

This doesn't compile.

#### Example

```java
  @Test
  void gt() {
    Comparable<String> s1 = that -> 1;
    Comparable<String> s2 = that -> 0;
    assertThat(s1).isGreaterThan(s2);
  }
```

**Comment by scordio** [comment] 2024-04-17 06:40
You're hitting two problems here:
* There is a known issue with generics (#2557) and you should use `assertThatComparable` if you must work with `Comparable` variables. We'll make it better in version 4.
* `isGreaterThan` expects a concrete `Comparable` value, i.e., a `String` in your example, so the compilation error is the correct behavior.

Closing as duplicate of #2557.

**Closed** 2024-04-17 06:41 UTC
Labels: status: duplicate

**Comment by scordio** [comment] 2024-04-17 07:46
@xenoterracide do you maybe have some real-life code that fails due to option 2, where providing a concrete value is not an option?

**Comment by xenoterracide** [comment] 2024-04-17 15:29
Not really no
