### ISSUE TITLE
`satisfies()` with nested assertions obscures stack trace

### ISSUE THREAD

**Issue by perlun** [assertj/assertj#2542] opened 2022-03-25 09:03 UTC
#### Summary
`satisfies()` with nested assertions obscures stack trace

#### Example

We have a `satisfies()` call with many embedded assertions like this. AssertJ doesn't expose the stack trace of the actual line that triggered the assertion in this case, only the `satisfies()` line:

```java
assertThat( tsdbDeviceMediator.getDeviceSnapshots( 1 ) )
        .singleElement()
        .satisfies( tsdbDevice -> {
            assertThat( tsdbDevice.getRevision() ).isEqualTo( 1 );
            assertThat( tsdbDevice.getPlatform() ).isEqualTo( "IOS" );
            assertThat( tsdbDevice.getProfile() ).isEqualTo( "ios" );
            assertThat( tsdbDevice.getProfileOverrides() ).isEqualTo( "IOS" );
            assertThat( tsdbDevice.getModel() ).isEqualTo( "IOS" );
            assertThat( tsdbDevice.getFirmwareVersion() ).isEqualTo( "IOS" );
            assertThat( tsdbDevice.getSerialNumber() ).isEqualTo( "IOS" );
            assertThat( tsdbDevice.isDynamicIpAddress() ).isEqualTo( "IOS" );
            assertThat( tsdbDevice.getIpAddress() ).isEqualTo( "IOS" );
            assertThat( tsdbDevice.getMacAddress() ).isEqualTo( "IOS" );
            assertThat( tsdbDevice.getSecondaryMacAddress() ).isEqualTo( "IOS" );
            assertThat( tsdbDevice.getAlias() ).isEqualTo( "IOS" );
            assertThat( tsdbDevice.getTvModelId() ).isEqualTo( "IOS" );
            assertThat( tsdbDevice.getDisplayMode() ).isEqualTo( "IOS" );
            assertThat( tsdbDevice.getSkinResolution() ).isEqualTo( "IOS" );
            assertThat( tsdbDevice.getMaxAgeRating() ).isEqualTo( "IOS" );
            assertThat( tsdbDevice.isTombstone() ).isFalse();
        } );
```

Here's what it looks like when I run this in IntelliJ. Line 222 is highlighted in the stack trace, but not the actual exception-triggering line:

![image](https://user-images.githubusercontent.com/630613/160089235-895f0e74-2041-430b-9567-b207a2b0f046.png)

Interestingly enough, if I wrap this in a `try`/`catch` like below and rethrow it as a `RuntimeException`, it starts working much better:

```java
assertThat( tsdbDeviceMediator.getDeviceSnapshots( 1 ) )
        .singleElement()
        .satisfies( tsdbDevice -> {
            try {
                assertThat( tsdbDevice.getRevision() ).isEqualTo( 1 );
                assertThat( tsdbDevice.getPlatform() ).isEqualTo( "IOS" );
                assertThat( tsdbDevice.getProfile() ).isEqualTo( "ios" );
                assertThat( tsdbDevice.getProfileOverrides() ).isEqualTo( "IOS" );
                assertThat( tsdbDevice.getModel() ).isEqualTo( "IOS" );
                assertThat( tsdbDevice.getFirmwareVersion() ).isEqualTo( "IOS" );
                assertThat( tsdbDevice.getSerialNumber() ).isEqualTo( "IOS" );
                assertThat( tsdbDevice.isDynamicIpAddress() ).isEqualTo( "IOS" );
                assertThat( tsdbDevice.getIpAddress() ).isEqualTo( "IOS" );
                assertThat( tsdbDevice.getMacAddress() ).isEqualTo( "IOS" );
                assertThat( tsdbDevice.getSecondaryMacAddress() ).isEqualTo( "IOS" );
                assertThat( tsdbDevice.getAlias() ).isEqualTo( "IOS" );
                assertThat( tsdbDevice.getTvModelId() ).isEqualTo( "IOS" );
                assertThat( tsdbDevice.getDisplayMode() ).isEqualTo( "IOS" );
                assertThat( tsdbDevice.getSkinResolution() ).isEqualTo( "IOS" );
                assertThat( tsdbDevice.getMaxAgeRating() ).isEqualTo( "IOS" );
                assertThat( tsdbDevice.isTombstone() ).isFalse();
            }
            catch ( Throwable t ) {
                throw new RuntimeException( t );
            }
        } );
```

Line 227 is properly listed in the stack trace, making it much easier to debug the actual cause of the problem:

![image](https://user-images.githubusercontent.com/630613/160089417-6facea93-fba8-44b0-80ac-752d09da613a.png)

### Conclusion

Could this be a bug in IntellIJ or AssertJ? :thinking: I tried playing with `Assertions.setRemoveAssertJRelatedElementsFromStackTrace(false)` but it didn't seem to affect this.

**Comment by joel-costigliola** [comment] 2022-03-26 04:41
Thanks for the detailed report, `Assertions.setRemoveAssertJRelatedElementsFromStackTrace(false)` is a good step to make sure AssertJ does not truncate the stack trace.
I'll try to reproduce the issue in eclipse to see if this IDE specific or not.

**Comment by joel-costigliola** [comment] 2022-03-26 05:32
the issue relates to https://github.com/assertj/assertj-core/issues/2067, when building the `AssertJMultipleFailuresError` message we build a summary of all the underlying errors but not their stacktrace, so what you get is only the `AssertJMultipleFailuresError` stack trace (which points to the `satisfies` call).

**Comment by joel-costigliola** [comment] 2022-03-26 05:37
@perlun  I'm closing this issue in favor of https://github.com/assertj/assertj-core/issues/2067 but feel free to continue commenting on it if you feel this is not the best solution.

**Comment by perlun** [comment] 2022-04-12 12:47
@joel-costigliola Thanks for the effort, appreciated! We don't use the multi-lambda with `.satisfies()` at the moment, and given that we have a number of assertions in these lambdas (17 in our local example I'm looking at for the moment), I'm not sure if it would be a great fit (and I'm not even sure if's required or if the fix for #2067 will help in our kind of use case as well?). But, I'm willing to give it a try.

Let me know once 3.23 has been released and I can test with our code base. :+1: Thanks again for looking into this.

**Comment by joel-costigliola** [comment] 2022-04-13 09:44
we aim to release 3.23.0 at the end of month but in software development there are "sometimes" delays :smile: .

**Comment by upsidedownsmile** [comment] 2024-05-16 09:28
@joel-costigliola I'm still seeing this problem in the latest version(3.25.3)

Code:
```
import static org.assertj.core.api.Assertions.assertThat;

import java.util.List;
import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.Test;

public class AssertJNestedTest {

  @Test
  public void test() {
    Assertions.setRemoveAssertJRelatedElementsFromStackTrace(false);

    List<Integer> list = List.of(1, 2, 3, 4);
    assertThat(list)
        .satisfiesOnlyOnce(
            n -> {
              isFive(n);
            });
  }

  private static void isFive(int n) {
    assertThat(n).isEqualTo(5);
  }
}
```

Exception
```
AssertJNestedTest > test() FAILED
    java.lang.AssertionError:
    Expecting exactly one element of actual:
      [1, 2, 3, 4]
    to satisfy the requirements but none did
        at org.assertj.core.error.AssertionErrorCreator.assertionError(AssertionErrorCreator.java:93)
        at org.assertj.core.internal.Failures.failure(Failures.java:126)
        at org.assertj.core.internal.Iterables.assertSatisfiesOnlyOnce(Iterables.java:1241)
        at org.assertj.core.api.AbstractIterableAssert.satisfiesOnlyOnceForProxy(AbstractIterableAssert.java:3998)
        at org.assertj.core.api.AbstractIterableAssert.satisfiesOnlyOnce(AbstractIterableAssert.java:3991)
        at software.amazon.opentelemetry.appsignals.test.jdbc.AssertJNestedTest.test(AssertJNestedTest.java:32)
```

In this case I would expect the stacktrace to point to the assert inside the `isFive` method(line 39), but instead it is pointing to the outter assert.

Let me know if I'm missing something here or if there is already a way to show the actual failed assertion in the stack trace.

**Comment by scordio** [comment] 2024-05-17 15:46
@upsidedownsmile it seems to be a separate issue of `satisfiesOnlyOnce` so I raised #3480.

**Comment by upsidedownsmile** [comment] 2024-05-17 15:58
@scordio thanks for creating a new issue, I thought it was related with this one.  
I'll take a look at https://github.com/assertj/assertj/issues/3480 to know when it will be solved.

**Comment by bbottema** [comment] 2024-11-15 08:08
I'm still having this issue with `.satisfiesExactly`. I lose the information in the stacktrace which nested `assertThat` failed.

**Comment by scordio** [comment] 2024-11-15 08:09
Hi @bbottema, could you please share a small reproducer?

**Comment by bbottema** [comment] 2024-11-15 08:32
Here you go:
```java
public class SatisfiesExactlyTest {

    @Test
    public void testSatisfiesExactlyLogging() {
        Assertions.setRemoveAssertJRelatedElementsFromStackTrace(false);

        A result = new A().b(List.of(new B().field1ToAssert("123").field2ToAssert("123")));

        assertThat(result)
                .satisfies(a -> assertThat(a.getB())
                    .satisfiesExactly(b -> { // <-- closest in the stacktrace is this line
                        assertThat(b.getField1ToAssert()).isEqualTo("999");
                        assertThat(b.getField2ToAssert()).isEqualTo("999");
                    }));
    }

    public static class A {
        private List<B> b = new ArrayList<>();

        public A b(List<B> artikelenStrafbaarfeit) {
            this.b = artikelenStrafbaarfeit;
            return this;
        }

        public List<B> getB() {
            return this.b;
        }
    }

    public static class B {
        private String field1ToAssert;
        private String field2ToAssert;

        public B field1ToAssert(String value) { this.field1ToAssert = value; return this; }
        public B field2ToAssert(String value) { this.field2ToAssert = value; return this; }

        public String getField1ToAssert() { return this.field1ToAssert; }
        public String getField2ToAssert() { return this.field2ToAssert; }
    }
}
```

**Comment by scordio** [comment] 2024-11-15 08:34
Thanks! We'll look into it.

**Comment by joel-costigliola** [comment] 2024-12-07 13:51
@bbottema I'm experimenting with including (limited) stack traces, I came up with the following 
```
java.lang.AssertionError: 
Expecting each element of:
  [B[field1=123, field2=123]]
to satisfy the requirements at its index, but these elements did not:

B[field1=123, field2=123]
- element index: 0
- error: org.opentest4j.AssertionFailedError: 
expected: "999"
 but was: "123"
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.assertj.core.error.ConstructorInvoker.newInstance(ConstructorInvoker.java:28)
	at org.assertj.core.error.ShouldBeEqual.assertionFailedError(ShouldBeEqual.java:223)
	at org.assertj.core.error.ShouldBeEqual.newAssertionError(ShouldBeEqual.java:122)
	at org.assertj.core.internal.Failures.failure(Failures.java:105)
	at org.assertj.core.internal.Objects.assertEqual(Objects.java:220)
	at org.assertj.core.api.AbstractAssert.isEqualTo(AbstractAssert.java:369)
	at org.assertj.core.api.AbstractStringAssert.isEqualTo(AbstractStringAssert.java:416)
	...(87 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)
<Click to see difference>


	at org.assertj.core.error.AssertionErrorCreator.assertionError(AssertionErrorCreator.java:92)
	at org.assertj.core.internal.Failures.failure(Failures.java:126)
	at org.assertj.core.internal.Iterables.assertSatisfiesExactly(Iterables.java:1214)
	at org.assertj.core.api.AbstractIterableAssert.satisfiesExactlyForProxy(AbstractIterableAssert.java:3952)
	at org.assertj.core.api.AbstractIterableAssert.satisfiesExactly(AbstractIterableAssert.java:3945)
	at org.assertj.core.api.abstract_.AbstractAssert_satisfies_with_Consumers_Test.lambda$testSatisfiesExactlyLogging$18(AbstractAssert_satisfies_with_Consumers_Test.java:132)
	at org.assertj.core.api.ThrowingConsumer.accept(ThrowingConsumer.java:31)
	at org.assertj.core.api.AbstractAssert.catchOptionalAssertionError(AbstractAssert.java:908)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.assertj.core.api.AbstractAssert.satisfiesForProxy(AbstractAssert.java:899)
	at org.assertj.core.api.AbstractAssert.satisfies(AbstractAssert.java:888)
	at org.assertj.core.api.abstract_.AbstractAssert_satisfies_with_Consumers_Test.testSatisfiesExactlyLogging(AbstractAssert_satisfies_with_Consumers_Test.java:131)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:767)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$8(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:156)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:146)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:144)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:100)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:160)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:146)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:144)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:100)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:160)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:146)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:144)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:100)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:198)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:169)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:93)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:58)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:141)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:57)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:103)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:85)
	at org.junit.platform.launcher.core.DelegatingLauncher.execute(DelegatingLauncher.java:47)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:63)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)


org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (1 failure)
-- failure 1 --
Expecting each element of:
  [B[field1=123, field2=123]]
to satisfy the requirements at its index, but these elements did not:

B[field1=123, field2=123]
- element index: 0
- error: org.opentest4j.AssertionFailedError: 
expected: "999"
 but was: "123"
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.assertj.core.error.ConstructorInvoker.newInstance(ConstructorInvoker.java:28)
	at org.assertj.core.error.ShouldBeEqual.assertionFailedError(ShouldBeEqual.java:223)
	at org.assertj.core.error.ShouldBeEqual.newAssertionError(ShouldBeEqual.java:122)
	at org.assertj.core.internal.Failures.failure(Failures.java:105)
	at org.assertj.core.internal.Objects.assertEqual(Objects.java:220)
	at org.assertj.core.api.AbstractAssert.isEqualTo(AbstractAssert.java:369)
	at org.assertj.core.api.AbstractStringAssert.isEqualTo(AbstractStringAssert.java:416)
	...(87 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)

	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.assertj.core.error.ConstructorInvoker.newInstance(ConstructorInvoker.java:28)
	at org.assertj.core.error.AssertionErrorCreator.tryBuildingMultipleFailuresError(AssertionErrorCreator.java:137)
	at org.assertj.core.error.AssertionErrorCreator.multipleAssertionsError(AssertionErrorCreator.java:104)
	at org.assertj.core.api.AbstractAssert.multipleAssertionsError(AbstractAssert.java:1005)
	at org.assertj.core.api.AbstractAssert.satisfiesForProxy(AbstractAssert.java:901)
	at org.assertj.core.api.AbstractAssert.satisfies(AbstractAssert.java:888)
	at org.assertj.core.api.abstract_.AbstractAssert_satisfies_with_Consumers_Test.testSatisfiesExactlyLogging(AbstractAssert_satisfies_with_Consumers_Test.java:131)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

```

It shows the stack trace of the unmet assertion for `assertThat(b.getField1()).isEqualTo("999")`.

Is that what you would like to have?

**Comment by bbottema** [comment] 2024-12-07 14:18
It doesn't seem like it would solve the issue. The failing assertion is 'described' in the output, but which assertion _exactly_ (which line) still seems to be missing.

In my case, I have many similar assertions, with large `toString()` output, so I'm getting completely lost currently without the exact failing assertion statement in the stack trace.

**Comment by bbottema** [comment] 2024-12-07 14:18
It doesn't seem like it would solve the issue. The failing assertion is _described_ in the output, but which assertion _exactly_ (which line) still seems to be missing.

In my case, I have many similar assertions, with large `toString()` output, so I'm getting completely lost currently without the exact failing assertion statement in the stack trace.

**Comment by joel-costigliola** [comment] 2024-12-07 15:04
Ah! it turns out that the default stack trace limit was too low to show the line where the inner assertion failed, by increasing it with
```java
    Assertions.setMaxStackTraceElementsDisplayed(50);
```
With 50 stack elements shown, I get 
```
java.lang.AssertionError: 
Expecting each element of:
  [B[field1=123, field2=123]]
to satisfy the requirements at its index, but these elements did not:

B[field1=123, field2=123]
- element index: 0
- error: org.opentest4j.AssertionFailedError: 
expected: "999"
 but was: "123"
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.assertj.core.error.ConstructorInvoker.newInstance(ConstructorInvoker.java:28)
	at org.assertj.core.error.ShouldBeEqual.assertionFailedError(ShouldBeEqual.java:223)
	at org.assertj.core.error.ShouldBeEqual.newAssertionError(ShouldBeEqual.java:122)
	at org.assertj.core.internal.Failures.failure(Failures.java:105)
	at org.assertj.core.internal.Objects.assertEqual(Objects.java:220)
	at org.assertj.core.api.AbstractAssert.isEqualTo(AbstractAssert.java:370)
	at org.assertj.core.api.AbstractStringAssert.isEqualTo(AbstractStringAssert.java:416)
	at org.assertj.core.api.abstract_.AbstractAssert_satisfies_with_Consumers_Test.lambda$testSatisfiesExactlyLogging$17(AbstractAssert_satisfies_with_Consumers_Test.java:134)
	at org.assertj.core.api.ThrowingConsumer.accept(ThrowingConsumer.java:31)
	at org.assertj.core.internal.Iterables.failsRequirements(Iterables.java:1194)
	at org.assertj.core.internal.Iterables.assertSatisfiesExactly(Iterables.java:1211)
	at org.assertj.core.api.AbstractIterableAssert.satisfiesExactlyForProxy(AbstractIterableAssert.java:3952)
	at org.assertj.core.api.AbstractIterableAssert.satisfiesExactly(AbstractIterableAssert.java:3945)
	at org.assertj.core.api.abstract_.AbstractAssert_satisfies_with_Consumers_Test.lambda$testSatisfiesExactlyLogging$18(AbstractAssert_satisfies_with_Consumers_Test.java:133)
	at org.assertj.core.api.ThrowingConsumer.accept(ThrowingConsumer.java:31)
	at org.assertj.core.api.AbstractAssert.catchOptionalAssertionError(AbstractAssert.java:948)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.assertj.core.api.AbstractAssert.satisfiesForProxy(AbstractAssert.java:939)
	at org.assertj.core.api.AbstractAssert.satisfies(AbstractAssert.java:928)
	at org.assertj.core.api.abstract_.AbstractAssert_satisfies_with_Consumers_Test.testSatisfiesExactlyLogging(AbstractAssert_satisfies_with_Consumers_Test.java:132)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:767)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$8(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	...(47 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)
```
where this stack element:
``` org.assertj.core.api.abstract_.AbstractAssert_satisfies_with_Consumers_Test.lambda$testSatisfiesExactlyLogging$17(AbstractAssert_satisfies_with_Consumers_Test.java:134)
```
points to the failing inner assertion: ![Image](https://github.com/user-attachments/assets/4e8056ed-4a8a-4f02-9c7a-8356fcbe4893)

I'm not sure how we could do better, since the overall message has to reflect the multiple level of embedded assertions with `satisfies` and `satisfiesExactly`, but ideas welcome!

**Comment by bbottema** [comment] 2024-12-09 05:51
I see. Yes this would work. Thank you for looking into this, I wasn't aware of this option.

**Closed** 2024-12-15 17:35 UTC
