### ISSUE TITLE
Failed containsOnlyNulls Assertion for Null-Extracted List Elements

### ISSUE THREAD

**Issue by laisbento** [assertj/assertj#3465] opened 2024-05-08 09:30 UTC
**Describe the bug**
There is an unexpected failure in `containsOnlyNulls` when asserting the nullity of fields within a list extracted using `extracting` fields. The assertion fails even though the extracted list elements are verifiably null, suggesting a discrepancy in how `containsOnlyNulls` processes list outputs from `extracting`.

* assertj core version: 3.24.2
* java version: 17
* test framework version:

**Test case reproducing the bug**
Create a class `ChildrenGroupComparisonTest` with fields `Long id`, `Set<String> fullNames`, and `List<Long> ages`.
Instantiate an object of `CurrencyGroupComparisonTest`, setting only the `id` field to a non-null value (e.g., 1L) and leaving the rest as null.
Create a list of `CurrencyGroupComparisonTest` and add the previous object in the list.
Use AssertJ's extracting to extract the `fullNames`, `ages`.
Apply `containsOnlyNulls `on the result.

**Test**

```java
    @Test
    void test() {
        var childrenGroupComparisonTest = new ChildrenGroupComparisonTest();
        childrenGroupComparisonTest.setId(1L); // Set only id to non-null

        var testList = new ArrayList<ChildrenGroupComparisonTest>();
        testList.add(childrenGroupComparisonTest);

        assertThat(testList)
                .extracting("fullNames", "ages")
                .containsOnlyNulls(); // Fails unexpectedly
    }
```

**Expected Result:**

The test should pass, confirming that all extracted fields except `id` are null.

**Actual Result:**

The test fails with an error message indicating that the expectation to contain only null elements is not met, despite the actual extracted results showing [(null, null)] which suggests that all fields are indeed null.

```
java.lang.AssertionError: 
Expecting code not to raise a throwable but caught
  "java.lang.AssertionError: [Extracted: fullNames, ages] 
Expecting actual:
  [(null, null)]
to contain only null elements but some elements were not:
  [(null, null)]
  ```

**Comment by joel-costigliola** [comment] 2024-05-08 10:12
Thanks for reporting this @laisbento, we'll have a stab at it for the next release !

**Comment by joel-costigliola** [comment] 2024-05-09 22:21
This is not a bug, when extracting multiple values AssertJ returns a list of `Tuple`, each tuple corresponding to the extracted values of the iterable under test.  

The `extracting` [javadoc](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/AbstractIterableAssert.html#extracting(java.lang.String...)) shows the tuple role:
```java 
 // Build a list of TolkienCharacter, a TolkienCharacter has a name, and age and a Race (a specific class)
 // they can be public field or properties, both can be extracted.
 List<TolkienCharacter> fellowshipOfTheRing = new ArrayList<TolkienCharacter>();

 fellowshipOfTheRing.add(new TolkienCharacter("Frodo", 33, HOBBIT));
 fellowshipOfTheRing.add(new TolkienCharacter("Sam", 38, HOBBIT));
 fellowshipOfTheRing.add(new TolkienCharacter("Gandalf", 2020, MAIA));
 fellowshipOfTheRing.add(new TolkienCharacter("Legolas", 1000, ELF));
 fellowshipOfTheRing.add(new TolkienCharacter("Pippin", 28, HOBBIT));
 fellowshipOfTheRing.add(new TolkienCharacter("Gimli", 139, DWARF));
 fellowshipOfTheRing.add(new TolkienCharacter("Aragorn", 87, MAN);
 fellowshipOfTheRing.add(new TolkienCharacter("Boromir", 37, MAN));

 // let's verify 'name' and 'age' of some TolkienCharacter in fellowshipOfTheRing:
 assertThat(fellowshipOfTheRing).extracting("name", "age")
                                .contains(tuple("Boromir", 37),
                                          tuple("Sam", 38),
                                          tuple("Legolas", 1000));
```
the `contains` assertion following `extracting` works with tuples.

In your case, I'm guessing what you wanted to do is to check the elements of the extracted fields, this is possible with `flatExtracting` that "flattens" the tuples values, here's the [javadoc](https://www.javadoc.io/static/org.assertj/assertj-core/3.25.3/org/assertj/core/api/AbstractIterableAssert.html#flatExtracting(java.lang.String...)):
```java
 // values are extracted in order and flattened: age1, name1, age2, name2, age3 ...
 assertThat(fellowshipOfTheRing).flatExtracting("age", "name")
                                .contains(33 ,"Frodo",
                                          1000, "Legolas",
                                          87, "Aragorn");
```
No tuples used with `flatExtracting`.

**Comment by joel-costigliola** [comment] 2024-05-11 21:25
@laisbento I'm closing this issue, but feel free to comment on it, and we'll reopen it if necessary.

**Closed by joel-costigliola** 2024-05-11 21:25 UTC
Labels: type: bug, status: invalid

**Comment by laisbento** [comment] 2024-05-13 06:09
Hello @joel-costigliola! Thanks for the explanation. I hadn't realized that `flatExtracting` existed. I've replaced for it in my tests and now everything is working as expected. I'll be using it from now on. :)
