### ISSUE TITLE
AbstractStringAssert isEqualTo throws when expected string contains % (percent mark)

### ISSUE THREAD

**Issue by kKapalka** [assertj/assertj#2916] opened 2023-01-12 08:55 UTC
Whenever I write a test which checks whether two strings containing a percent mark are equal, the test throws
java.util.MissingFormatArgumentException: Format specifier '%[text immediately following the percent mark]'

For the moment, I am forced to use matches() function instead, but I would like to be able to compare two strings just with isEqualTo(), just as I can do with other variable types.

If I'm using the isEqualTo() method incorrectly, please close the issue.

* assertj core version: 3.12.2
* java version: 8
* test framework version: 5.5.2
* os (if relevant): Windows
* language: Kotlin

```java
Assertions.assertThat("foo%bar").isEqualTo("foo%bar")
[...]
java.util.MissingFormatArgumentException: Format specifier '%b'
	at java.util.Formatter.format(Formatter.java:2519)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at org.assertj.core.api.AbstractStringAssert.isEqualTo(AbstractStringAssert.java:312)
```

**Comment by joel-costigliola** [comment] 2023-01-12 09:52
Thanks for reporting this @kKapalka !

**Comment by joel-costigliola** [comment] 2023-01-14 04:44
@kKapalka try the latest version where this has been fixed (I could not reproduce the bug in the latest version)

**Comment by scordio** [comment] 2023-01-16 10:52
Hi @kKapalka, as mentioned by @joel-costigliola, please upgrade to the latest version and try again.

I'm going to close this issue but happy to reopen it in case you encounter any issues.

**Closed by scordio** 2023-01-16 10:52 UTC
Labels: status: invalid

**Comment by kKapalka** [comment] 2023-01-16 10:53
Alrighty, thanks!
